# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_process <- function(args, async) {
    .Call(`_lasR_cpp_process`, args, async)
}

cpp_get_pipeline_info <- function(pipeline) {
    .Call(`_lasR_cpp_get_pipeline_info`, pipeline)
}

