name: pylasr Tests

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'python/**'
      - 'src/**'
      - '.github/workflows/pylasr.yaml'
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - 'python/**'
      - 'src/**'
      - '.github/workflows/pylasr.yaml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        #, windows-latest, macos-latest]
        python-version: ['3.11', '3.12', '3.13']
        
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gdal-bin \
          libgdal-dev \
          libgeos-dev \
          libproj-dev \
          libsqlite3-dev \
          libtbb-dev \
          cmake \
          build-essential

    - name: Install system dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install \
          gdal \
          geos \
          proj \
          sqlite \
          tbb \
          cmake

    - name: Install system dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        choco install sqlite
        # Note: GDAL, GEOS, PROJ installation on Windows might require vcpkg or conda

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel numpy

    - name: Build Python extension
      working-directory: python
      run: |
        python setup.py build_ext --inplace

    - name: Run tests
      working-directory: python
      run: |
        python tests/run_tests.py

    - name: Run quick smoke test
      working-directory: python
      run: |
        python tests/run_tests.py --quick

    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.os }}-${{ matrix.python-version }}
        path: python/tests/*.log
        retention-days: 7